[package]
name = "scca-solo-points-engine"
description = "Business logic for the SCCA Solo Points Calculator"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/DavidZemon/SccaSoloPointsCalculator"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src-rs/lib.rs"

[dependencies]
bigdecimal = "0.3.0"
calamine = "0.19.1"
csv = "1.2.1"
float-cmp = "0.9.0"
lazy_static = "1.4.0"
js-sys = "0.3.61"
regex = "1.7.3"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
serde-wasm-bindgen = "0.5.0"
strum = "0.24.1"
strum_macros = "0.24.3"
wasm-bindgen = { version = "0.2.84", features = ["serde-serialize"] }

[dev-dependencies]
rstest = "0.17.0"
mockall = "0.11.4"
