[package]
name = "rusty"
description = "Business logic for the SCCA Solo Points Calculator"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/DavidZemon/SccaSoloPointsCalculator"

[lib]
crate-type = ["cdylib"]
path = "src-rs/lib.rs"

[dependencies]
csv = "1.1.6"
float-cmp = "0.9.0"
getset = "0.1.2"
lazy_static = "1.4.0"
serde = {version = "1.0.137", features = ["derive"]}
wasm-bindgen = "^0.2.80"
